// generated by "sampctl package init"

#define FILTERSCRIPT 

#include <a_samp>

#include "multicp.inc"

new multicp[2];

main() 
{

}

public OnPlayerSpawn(playerid)
{
	SetPlayerPos(playerid, 2220.4258,-1458.9979,24.0000);

	multicp[0] = SetPlayerMultiCP(playerid, 2211.3108,-1452.9723,23.8193, true); // created multiCP with auto disable when entered (like normal CP)
	multicp[1] = SetPlayerMultiCP(playerid, 2212.1157,-1460.9147,23.8205, false);
	return 1;
}

public OnPlayerEnterMultiCP(playerid, cpid) {
	printf("Entered MultiCP %d", cpid);
	return 1;
}

public OnPlayerLeaveMultiCP(playerid, cpid) {
	printf("Leaved MultiCP %d", cpid);
	return 1;
}
